insert into users (userName,userPassword) values ('daddy','lowks');
insert into users (userName,userPassword) values ('yerr','lowks');
insert into run (userId, category, firstDigit, secondDigit, correct, timeElapsed) values (1,  '2x2', 15, 17, true, 10);
insert into run (userId, category, firstDigit, secondDigit, correct, timeElapsed) values (1,  '2x2', 15, 17, true, 10);
insert into run (userId, category, firstDigit, secondDigit, correct, timeElapsed) values (1,  '2x2', 15, 17, true, 10);
insert into run (userId, category, firstDigit, secondDigit, correct, timeElapsed) values (1,  '2x2', 15, 17, true, 10);
insert into run (userId, category, firstDigit, secondDigit, correct, timeElapsed) values (1,  '2x2', 15, 17, true, 10);
insert into run (userId, category, firstDigit, secondDigit, correct, timeElapsed) values (2,  '2x2', 15, 17, true, 10);
insert into run (userId, category, firstDigit, secondDigit, correct, timeElapsed) values (2,  '2x2', 15, 17, false, 10);
insert into run (userId, category, firstDigit, secondDigit, correct, timeElapsed) values (2,  '2x2', 15, 17, false, 10);
